library verilog;
use verilog.vl_types.all;
entity T80_MCode is
    generic(
        Mode            : integer := 0;
        Flag_C          : integer := 0;
        Flag_N          : integer := 1;
        Flag_P          : integer := 2;
        Flag_X          : integer := 3;
        Flag_H          : integer := 4;
        Flag_Y          : integer := 5;
        Flag_Z          : integer := 6;
        Flag_S          : integer := 7
    );
    port(
        IR              : in     vl_logic_vector(7 downto 0);
        ISet            : in     vl_logic_vector(1 downto 0);
        MCycle          : in     vl_logic_vector(2 downto 0);
        F               : in     vl_logic_vector(7 downto 0);
        NMICycle        : in     vl_logic;
        IntCycle        : in     vl_logic;
        XY_State        : in     vl_logic_vector(1 downto 0);
        MCycles         : out    vl_logic_vector(2 downto 0);
        TStates         : out    vl_logic_vector(2 downto 0);
        Prefix          : out    vl_logic_vector(1 downto 0);
        Inc_PC          : out    vl_logic;
        Inc_WZ          : out    vl_logic;
        IncDec_16       : out    vl_logic_vector(3 downto 0);
        Read_To_Reg     : out    vl_logic;
        Read_To_Acc     : out    vl_logic;
        Set_BusA_To     : out    vl_logic_vector(3 downto 0);
        Set_BusB_To     : out    vl_logic_vector(3 downto 0);
        ALU_Op          : out    vl_logic_vector(3 downto 0);
        Save_ALU        : out    vl_logic;
        PreserveC       : out    vl_logic;
        Arith16         : out    vl_logic;
        Set_Addr_To     : out    vl_logic_vector(2 downto 0);
        IORQ            : out    vl_logic;
        Jump            : out    vl_logic;
        JumpE           : out    vl_logic;
        JumpXY          : out    vl_logic;
        Call            : out    vl_logic;
        RstP            : out    vl_logic;
        LDZ             : out    vl_logic;
        LDW             : out    vl_logic;
        LDSPHL          : out    vl_logic;
        Special_LD      : out    vl_logic_vector(2 downto 0);
        ExchangeDH      : out    vl_logic;
        ExchangeRp      : out    vl_logic;
        ExchangeAF      : out    vl_logic;
        ExchangeRS      : out    vl_logic;
        I_DJNZ          : out    vl_logic;
        I_CPL           : out    vl_logic;
        I_CCF           : out    vl_logic;
        I_SCF           : out    vl_logic;
        I_RETN          : out    vl_logic;
        I_BT            : out    vl_logic;
        I_BC            : out    vl_logic;
        I_BTR           : out    vl_logic;
        I_RLD           : out    vl_logic;
        I_RRD           : out    vl_logic;
        I_INRC          : out    vl_logic;
        SetDI           : out    vl_logic;
        SetEI           : out    vl_logic;
        IMode           : out    vl_logic_vector(1 downto 0);
        Halt            : out    vl_logic;
        NoRead          : out    vl_logic;
        Write           : out    vl_logic;
        XYbit_undoc     : out    vl_logic
    );
    attribute mti_svvh_generic_type : integer;
    attribute mti_svvh_generic_type of Mode : constant is 1;
    attribute mti_svvh_generic_type of Flag_C : constant is 1;
    attribute mti_svvh_generic_type of Flag_N : constant is 1;
    attribute mti_svvh_generic_type of Flag_P : constant is 1;
    attribute mti_svvh_generic_type of Flag_X : constant is 1;
    attribute mti_svvh_generic_type of Flag_H : constant is 1;
    attribute mti_svvh_generic_type of Flag_Y : constant is 1;
    attribute mti_svvh_generic_type of Flag_Z : constant is 1;
    attribute mti_svvh_generic_type of Flag_S : constant is 1;
end T80_MCode;
