#!/bin/sh
# Build and program the board, refusing to program a build that did not
# close timing.
#
# The 112MHz SDRAM attempt was programmed with a setup slack of -1.85ns
# because the checks here only looked at the map/fit/asm exit codes.
# Quartus reports a timing failure as a critical warning and still exits
# 0, so the board got a build that could not work - it came up showing
# the no-ROM pattern. Timing now blocks programming the same way a
# compile error does.
#
#   ./build.sh          build, check timing, program
#   ./build.sh --no-pgm build and check only
set -e

export PATH=/c/altera/13.1/quartus/bin64:$PATH
cd "$(dirname "$0")"

quartus_map spectrum > /dev/null 2>&1 || { echo "ANALYSIS FAILED"; exit 1; }
quartus_fit spectrum > /dev/null 2>&1 || { echo "FIT FAILED";      exit 1; }
quartus_asm spectrum > /dev/null 2>&1 || { echo "ASSEMBLE FAILED"; exit 1; }

sta=$(quartus_sta spectrum 2>&1)
echo "$sta" | grep -E "Worst-case (setup|hold) slack" | sed 's/^ *//'

if echo "$sta" | grep -q "Timing requirements not met"; then
	echo "TIMING NOT MET - not programming."
	echo "$sta" | grep -A 12 "Report Timing.*setup" | head -20
	exit 2
fi


# The pair that gets kept: dated, and stamped with the commit it was
# built from, so a board in hand can always be traced back to a tree.
# Quartus names its own output after the revision, which says nothing
# about when or from what.
stamp=$(date +%Y%m%d)
hash=$(git rev-parse --short=4 HEAD 2>/dev/null || echo 0000)
# A build from a modified tree is not the commit it names, so say so.
# Without this the pair carries the hash of the last commit while its
# contents are something else entirely - the one thing the naming exists
# to prevent.
git diff --quiet HEAD 2>/dev/null || hash="$hash-dirty"
name="release/$stamp-$hash"

cp release/spectrum.sof "$name.sof"
# EPCS16 is what this board carries - see the device line in the .cdf
# Quartus writes for it.
quartus_cpf -c -d EPCS16 release/spectrum.sof "$name.pof" > /dev/null 2>&1 ||
	{ echo "POF CONVERSION FAILED"; exit 3; }
echo "release: $(basename "$name").sof + .pof"

# What the build cost, read out before the reports are swept away.
grep -hE "Total logic elements|Total memory bits" release/spectrum.fit.rpt |
	head -2 |
	awk -F';' '{ gsub(/^ +| +$/,"",$2); gsub(/^ +| +$/,"",$3); print $2 ": " $3 }'

# release/ holds the finished pairs and nothing else. Quartus fills it
# with reports, summaries and its own revision-named .sof on every run;
# all of that is regenerated by the next build and none of it belongs in
# a folder whose point is "these are the images that were released".
find release -maxdepth 1 -type f \
	! -name '20??????-????.sof' ! -name '20??????-????.pof' -delete

[ "$1" = "--no-pgm" ] && { echo "timing met, not programming"; exit 0; }

quartus_pgm -c USB-Blaster -m JTAG -o "p;$name.sof" 2>&1 |
	grep -E "successful|Error"
